---
title: "maps"
author: "Connor"
date: "4/25/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(urbnmapr)
library(here)
library(plotly)
library(ggiraph)
library(sf)


```

```{r}
territories_states <- get_urbn_map(map = "territories_states", sf = TRUE)

ggplot() +
  geom_sf(territories_states,
          mapping = aes(),
          fill = "grey", color = "#ffffff")
```


```{r}
mariana_islands <- territories_states[territories_states$state_name == "Mariana Islands", ]
```

```{r}
# Increase the size of the Mariana Islands
enlarged_mariana_islands <- st_cast(mariana_islands, "POLYGON")  # Convert the islands to polygons
enlarged_mariana_islands <- scale(enlarged_mariana_islands$geometry, 2, center = st_centroid(enlarged_mariana_islands$geometry))  # Scale the polygons by a factor of 2

```

```{r}
ggplot() +
  geom_sf(data = territories_states, fill = "grey", color = "#ffffff") +
  geom_sf(data = enlarged_mariana_islands, fill = "grey", color = "#ffffff")
```


```{r}
hospital_info <- read_csv(here("data/hospital_info_us.csv"))

```


```{r}
hospital_info <- hospital_info %>%
  separate(State, into = c("State", "State_Name"), sep = " - ") %>%
  select(-State_Name)
```

```{r}
hospital_info <- hospital_info %>%
  rename(state_abbv = State)
```

```{r}
spatial_data <- left_join(get_urbn_map(map = "territories_states", sf = TRUE),
                          hospital_info,
                          by = "state_abbv")
```

```{r}
spatial_data <- spatial_data %>%
  mutate(
    tooltip_text = paste0(toupper(state_name), "\n", 
                   ratio)
  )
```

```{r}

plota <- ggplot(spatial_data) +
  geom_sf(spatial_data,
          mapping = aes(fill = ratio),
          color = "#ffffff", size = 0.25) +
  labs(fill = "Ratio of Population to Staffed Hospital Beds") +
   coord_sf(datum = NA)+
  #geom_sf_text(data = get_urbn_labels(map = "territories_states", sf = TRUE), 
                #aes(label = state_abbv), 
            #size = 3) +
   theme_minimal() +
  theme(panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank()) 

plota
   
```


```{r}
plotb <- ggplot(spatial_data) +
  geom_sf_interactive(spatial_data,
          mapping = aes(fill = ratio, tooltip = tooltip_text, data_id = state_name),
          color = "#ffffff", size = 0.25) +
  labs(fill = "Ratio of Population to Staffed Hospital Beds") +
   coord_sf(datum = NA)+
  #geom_sf_text(data = get_urbn_labels(map = "territories_states", sf = TRUE), 
                #aes(label = state_abbv), 
            #size = 3) +
   theme_minimal() +
  theme(panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank()) 

plotb
```

```{r}
girafe(ggobj = plotb)
```



Edit Geometries





